"""Add unique constraint to title

Revision ID: c23007183490
Revises: 89a3fbb17d33
Create Date: 2025-05-05 18:38:36.942904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c23007183490"
down_revision: Union[str, None] = "89a3fbb17d33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tablets", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "tablets",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.create_unique_constraint("uq_tablet_title", "tablets", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_tablet_title", "tablets", type_="unique")
    op.alter_column(
        "tablets",
        "price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.alter_column("tablets", "title", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
